project:
  type: website
  resources:
    - CNAME

website:
  title: "r4ds.io"
  repo-url: https://github.com/r4ds/r4ds_app
  repo-actions: [edit, issue]
  navbar:
    tools:
      - icon: mastodon
        href: https://fosstodon.org/@R4DSCommunity
      - icon: linkedin
        href: https://www.linkedin.com/company/r4ds
      - icon: youtube
        href: https://r4ds.io/youtube
      - icon: github
        href: https://github.com/r4ds/r4ds_app
    left:
      - href: bookclubs.qmd
      - href: question_answering.qmd
      # - href: donate.qmd
      - text: About Us
        menu:
        - href: about.qmd
        - href: code_of_conduct.qmd
        - href: privacy.qmd
        - href: license.qmd
        - href: governance.qmd
  page-footer:
    background: "#222"
    center:
      This website is licensed under a [Creative Commons Attributions 4.0
      International License](https://creativecommons.org/licenses/by/4.0/).
      Copyright 2024 the Data Science Learning Community.

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: false
    link-external-newwindow: true
