project:
  type: website
  resources:
    - CNAME

website:
  title: "R4DS Online Learning Community"
  repo-url: https://github.com/r4ds/r4ds_app
  repo-actions: [edit, issue]
  google-analytics: "G-QQ1ZV766J5"
  cookie-consent: true
  navbar:
    # background: "#f0eeeb"
    # logo: images/r4ds-logo-150px.png
    # logo-alt: "R4DS Online Learning Community"
    # title: false
    tools:
      - icon: mastodon
        href: https://fosstodon.org/@R4DSCommunity
      - icon: linkedin
        href: https://www.linkedin.com/company/r4ds
      - icon: youtube
        href: https://r4ds.io/youtube
      - icon: github
        href: https://github.com/r4ds/r4ds_app
    left:
      - learn.qmd
      - text: Get Help
        menu:
        - slack.qmd
        - huhu.qmd
      - projects.qmd
      - donate.qmd
      - text: About Us
        menu:
        - about.qmd
        - code_of_conduct.qmd
        - privacy.qmd
        - license.qmd
        - governance.qmd
        - sponsor.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: false
    link-external-newwindow: true
