---
title: "Help Us Help You"
---

Help us help you!

Mentors (and other learners) in the R4DS Community will be better equipped to troubleshoot your issue or answer your question if you keep these tips in mind:

1.    Provide adequate background information: What are you trying to accomplish? What have you already tried? What error messages are you seeing (exactly, not paraphrased)? How is the output not what you’d expect?
2.    Post the minimal setup needed to expose the problem, if you can. Removing unrelated data and code will help us get to the core of your issue faster. Provide a small illustrative sample data frame and refer to its columns and values in your question.
3.    Make it runnable, if you can. Others should be able to copy and paste the code you post and run it in their own R session (assuming the right packages are installed, as identified in a `library()` call in your code). Investigate the `reprex` package.  Use `dput` to create runnable versions of R objects, or build easy-to-read tibbles with `tribble`.
4.    Format for readability, using Slack’s mini-markdown capabilities. Identify embedded snippets of R code by enclosing in single backticks (\`).  Example: My favorite `tidyverse` function is `mutate`. And format chunks of R code by enclosing multiple lines with pairs of triple-backticks (tip: ctrl+Enter puts a newline in your Slack post):

```
library(tidyverse)
tdf <- tribble(
  ~foo, ~bar,
  1, 2
  3, 4
)
```

For more ideas on posting questions/issues effectively, have a look at this [Posit Community guide](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219), and the [Issues Appendix from Tidyteam code review principles](https://code-review.tidyverse.org/issues/).
