on:
  push:
    branches: main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

name: Render and deploy site

jobs:
  render:
    if: startsWith(github.repository, 'r4ds/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up DESCRIPTION dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render & Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
